version: 2.1

orbs:
  pack: buildpacks/pack@dev:1f2a08e
workflows:
  version: 2
  main:
    jobs:
      - pack/build:
          working-directory: apps/java-maven
          image-name: cnbs/circleci-sample
          builder: 'cnbs/sample-builder:bionic'
      - test:
          requires:
            - pack/build

jobs:
  test:
    # load and run the created image
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/images/image.tgz
            docker run -d -p 8080:8080 cnbs/circleci-sample
            sleep 40
            curl -k localhost:8080